// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KarmoBlazorServerDB.Data.KarmoBlazorServer;

public partial class Temp
{
    public int Id { get; set; }

    public string Name { get; set; }
}