// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KarmoBlazorServerDB.Data.KarmoBlazorServer;

public partial class WeatherForecast
{
    public int Id { get; set; }

    public DateTime? Date { get; set; }

    public int? TemperatureC { get; set; }

    public int? TemperatureF { get; set; }

    public string Summary { get; set; }

    public string UserName { get; set; }
}