<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e330c57f-aa6d-41fc-aa06-c4689c339401</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mscc.GenerativeAI" Version="3.0.2" />
  </ItemGroup>

</Project>
