namespace KarmoLab.YawnBot.Models
{
	public enum BotMessageKey
	{
		Webhook_Ping_Title,
		Webhook_Ping_Desc,
		Webhook_Push_Title,
		Webhook_Issue_Title,
		Webhook_Issue_Desc,

		General_Ping_Title,
		General_Ping_Desc,
		General_Help_Title,
		General_Help_Prev,
		General_Help_Next,

		Help_Basic_Title,
		Help_Basic_Desc,
		Help_Basic_Content,
		Help_MiniGame_Title,
		Help_MiniGame_Desc,
		Help_MiniGame_Content,
		Help_Stock_Title,
		Help_Stock_Desc,
		Help_Stock_Content,
		Help_Raid_Title,
		Help_Raid_Desc,
		Help_Raid_Content,

		Common_Busy,

		Enhance_MaxLevel_Title,
		Enhance_MaxLevel_Desc,
		Enhance_Error_Title,
		Enhance_Error_Desc,
		Enhance_NoMoney_Title,
		Enhance_NoMoney_Cost,
		Enhance_NoMoney_Balance,
		Enhance_GreatSuccess_Title,
		Enhance_GreatSuccess_Desc,
		Enhance_Increase,
		Enhance_Blacksmith_Comment,
		Enhance_Lore,
		Enhance_Cost,
		Enhance_RemainingBalance,
		Enhance_News_Huge_Title,
		Enhance_News_Huge_Desc,
		Enhance_Success_Title,
		Enhance_Success_Desc,
		Enhance_News_Great_Title,
		Enhance_News_Great_Desc,
		Enhance_Fail_Protected_Title,
		Enhance_Fail_Protected_Desc,
		Enhance_Fail_Title,
		Enhance_Fail_Desc,
		Enhance_Fail_Cost,

		Sell_NoSword_Title,
		Sell_NoSword_Desc,
		Sell_Appraising_Title,
		Sell_Appraising_Desc,
		Sell_Comment_Great,
		Sell_Comment_Bad,
		Sell_Comment_Good,
		Sell_Complete_Title,
		Sell_Complete_Desc,
		Sell_BasePrice,
		Sell_FinalPrice,
		Sell_Blacksmith_Eval,
		Sell_CurrentBalance,

		Info_Title,
		Info_SwordName,
		Info_MaxLevel,
		Info_Balance,
		Info_NoName,

		Money_Title,
		Money_Desc,

		Battle_TargetError_Title,
		Battle_NoTarget_Desc,
		Battle_Self_Desc,
		Battle_Bot_Desc,
		Battle_Limit_Title,
		Battle_Limit_Desc,
		Battle_Win_Title,
		Battle_Win_Desc,
		Battle_MySword,
		Battle_TargetSword,
		Battle_Reward,
		Battle_Remaining,
		Battle_Lose_Title,
		Battle_Lose_Desc,

		Rank_Title,
		Rank_NoData,
		Rank_UnknownUser,

		Attend_Complete_Title,
		Attend_Complete_Desc,
		Attend_CurrentBalance,
		Attend_Wait_Title,
		Attend_Wait_Desc,

		GMM_Title,
		GMM_Desc,
		GMM_Amount,

		Game_BetError,
		Game_NoMoney,

		Slot_Running_Title,
		Slot_Running_Desc,
		Slot_Result_Title,
		Slot_Bet,
		Slot_Earn,
		Slot_Balance,
		Slot_Jackpot,
		Slot_Diamond,
		Slot_Triple,
		Slot_Double,
		Slot_Lose,

		OddEven_Title,
		OddEven_Result,
		OddEven_Choice,
		OddEven_Bet,
		OddEven_Win,
		OddEven_Lose,
		OddEven_Odd,
		OddEven_Even,

		RPS_Title,
		RPS_User,
		RPS_Bot,
		RPS_Result,
		RPS_Win,
		RPS_Lose,
		RPS_Draw,

		Weapon_Unknown,
		Weapon_NoName,

		Raid_NoRaid_Title,
		Raid_NoRaid_Desc,
		Raid_Status_Title,
		Raid_Status_Desc,
		Raid_Clean_Title,
		Raid_Clean_Desc,
		Raid_Ranking_Title,
		Raid_Ranking_Format,

		Stock_Chart_Title,
		Stock_List_Title,
		Stock_List_Format,
		Stock_List_Change_Up,
		Stock_List_Change_Down,
		Stock_List_Change_None,
		Stock_Buy_AmountError,
		Stock_Buy_SymbolError,
		Stock_Buy_MoneyError,
		Stock_Buy_Success,
		Stock_Sell_NoStock,
		Stock_Sell_AmountError,
		Stock_Sell_Success,
		Stock_MyStock_Empty,
		Stock_MyStock_Header,
		Stock_MyStock_Item,
		Stock_MyStock_Footer,

		Meme_Title,
		Meme_Footer,

		Consolation_Title,
		Consolation_Desc,

		Admin_AccessDenied_Title,
		Admin_AccessDenied_Desc,
		Admin_Reload_Title,
		Admin_Reload_Desc,
		Admin_Save_Title,
		Admin_Save_Desc,

		Server_Startup_Greeting
	}
}
