// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace KarmoBlazorServerDB.Data.KarmoBlazorServer;

public partial class KarmoAppContext : DbContext
{
    public KarmoAppContext(DbContextOptions<KarmoAppContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UserRecord> UserRecord { get; set; }
    public virtual DbSet<SpecialThing> SpecialThing { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        /*modelBuilder.Entity<WeatherForecast>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WeatherF__3214EC0798D5A593");

            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Summary).HasMaxLength(50);
            entity.Property(e => e.UserName).HasMaxLength(50);
        });

        modelBuilder.Entity<Temp>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Animations");

            entity.Property(e => e.Name).HasColumnType("Name");
        });*/

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}