// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KarmoBlazorServerDB.Data.KarmoBlazorServer;

public enum SpecialThingType
{
    Game,
    Animation,
    Movie,
    Book,
    Manga,
}

public partial class SpecialThing
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Creator { get; set; }
    public int Type { get; set; }
    public DateTime Date { get; set; }

}
