// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KarmoBlazorServerDB.Data.KarmoBlazorServer;

public partial class UserRecord
{
    public int Id { get; set; }

    public string UserName { get; set; }
    public int SpecialThingId { get; set; }
    public DateTime Date { get; set; }
    public byte? Star { get; set; }
    public string? Comment { get; set; }
}